import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { motion, AnimatePresence } from 'framer-motion'
import { Heart, Search, MessageCircle, MapPin, Instagram, Sparkles, Crown, Gem, Phone, Menu, X, Star, ChevronLeft } from 'lucide-react'
import './styles/index.css'
import { products, categories, gallery, reviews } from './data/products'

const whatsappNumber = '967777000000'
const fadeUp = { hidden: { opacity: 0, y: 28 }, show: { opacity: 1, y: 0, transition: { duration: .7, ease: 'easeOut' } } }

function Navbar(){const [open,setOpen]=useState(false); const links=['الرئيسية','التصاميم','الفساتين','الجلابيات','المعرض','التواصل']; return <nav className="nav"><a className="brand" href="#home"><span>تصاميم</span><small>TASAMMEM</small></a><div className="nav-links">{links.map(l=><a key={l} href={`#${l==='الرئيسية'?'home':l}`}>{l}</a>)}</div><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><AnimatePresence>{open&&<motion.div className="mobile" initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}>{links.map(l=><a onClick={()=>setOpen(false)} key={l} href={`#${l==='الرئيسية'?'home':l}`}>{l}</a>)}</motion.div>}</AnimatePresence></nav>}
function Hero(){return <section id="home" className="hero"><div className="hero-glow"/><motion.div className="hero-copy" initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.15}}}}><motion.span variants={fadeUp} className="eyebrow"><Sparkles size={18}/> مجموعة مناسبات 2026</motion.span><motion.h1 variants={fadeUp}>أناقتك تبدأ من هنا</motion.h1><motion.p variants={fadeUp}>فساتين سهرة وجلابيات بتصاميم راقية تناسب أجمل مناسباتك، مختارة بعناية لتظهري بإطلالة لا تُنسى.</motion.p><motion.div variants={fadeUp} className="actions"><a href="#التصاميم" className="btn primary">تصفح التشكيلة</a><a href={`https://wa.me/${whatsappNumber}`} className="btn ghost">تواصل معنا</a></motion.div><motion.div variants={fadeUp} className="metrics"><span><b>+120</b> تصميم فاخر</span><span><b>24/7</b> طلب واتساب</span><span><b>VIP</b> خدمة عميلات</span></motion.div></motion.div><motion.div className="hero-card" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{duration:.9}}><img src="https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=900&q=85" alt="فستان سهرة فاخر"/><div className="floating"><Crown/> فستان سهرة ملكي</div></motion.div></section>}
function ProductCard({p,favs,toggle}){return <motion.article className="product" variants={fadeUp} whileHover={{y:-8}}><button className={`fav ${favs.includes(p.id)?'active':''}`} onClick={()=>toggle(p.id)} aria-label="إضافة للمفضلة"><Heart fill={favs.includes(p.id)?'currentColor':'none'}/></button><img src={p.image} alt={p.name}/><div className="product-body"><span className="tag">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="price-row"><b>{p.price}</b><a href={`#product-${p.id}`}>التفاصيل <ChevronLeft size={16}/></a></div><a className="whatsapp" href={`https://wa.me/${whatsappNumber}?text=${encodeURIComponent('أرغب بطلب '+p.name)}`}><MessageCircle size={18}/> طلب عبر واتساب</a></div></motion.article>}
function Products(){const [query,setQuery]=useState('');const [cat,setCat]=useState('الكل');const [favs,setFavs]=useState([]);const filtered=useMemo(()=>products.filter(p=>(cat==='الكل'||p.type===cat)&&(p.name.includes(query)||p.category.includes(query)||p.description.includes(query))),[query,cat]);const toggle=id=>setFavs(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);return <section id="التصاميم" className="section"><div className="section-head"><span className="eyebrow"><Gem size={18}/> أحدث التصاميم</span><h2>تشكيلة فاخرة جاهزة للطلب</h2><p>بحث وتصنيفات سهلة لتصل العميلة بسرعة للتصميم المناسب.</p></div><div className="toolbar"><label><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحثي عن فستان، جلابية، لون..."/></label><div>{categories.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div></div><motion.div className="grid" initial="hidden" whileInView="show" viewport={{once:true}} variants={{show:{transition:{staggerChildren:.08}}}}>{filtered.map(p=><ProductCard key={p.id} p={p} favs={favs} toggle={toggle}/>)}</motion.div></section>}
function SplitSection({id,title,text,img,reverse}){return <section id={id} className={`split ${reverse?'reverse':''}`}><motion.img src={img} alt={title} initial={{opacity:0,x:reverse?50:-50}} whileInView={{opacity:1,x:0}} viewport={{once:true}}/><motion.div initial="hidden" whileInView="show" viewport={{once:true}} variants={fadeUp}><span className="eyebrow"><Sparkles size={18}/> {id}</span><h2>{title}</h2><p>{text}</p><a className="btn primary" href="#التصاميم">شاهدي التصاميم</a></motion.div></section>}
function Why(){const items=[['تصاميم مختارة بعناية','قطع منتقاة بذوق يناسب المناسبات الراقية.'],['جودة عالية','أقمشة وتفاصيل تمنح الإطلالة حضورًا فخمًا.'],['إطلالتك أولويتنا','نساعدك في اختيار التصميم الملائم لمناسبتك.'],['خدمة عملاء مميزة','طلب سريع ومتابعة مباشرة عبر واتساب.']];return <section className="section why"><div className="section-head"><span className="eyebrow"><Crown size={18}/> لماذا تصاميم؟</span><h2>لأن الفخامة تبدأ من التفاصيل</h2></div><div className="why-grid">{items.map(([t,d])=><motion.div className="why-card" whileHover={{scale:1.03}} key={t}><Star/><h3>{t}</h3><p>{d}</p></motion.div>)}</div></section>}
function Gallery(){return <section id="المعرض" className="section"><div className="section-head"><h2>معرض الإلهام</h2><p>صور قابلة للاستبدال لاحقًا بصور التصاميم الحقيقية.</p></div><div className="gallery">{gallery.map((g,i)=><motion.img key={g} src={g} alt={`تصميم ${i+1}`} whileHover={{scale:1.04}} />)}</div></section>}
function Reviews(){return <section className="section blush"><div className="section-head"><h2>آراء العميلات</h2></div><div className="review-grid">{reviews.map(r=><article className="review" key={r.name}><div>★★★★★</div><p>“{r.text}”</p><b>{r.name}</b></article>)}</div></section>}
function Details(){return <section className="section details"><div className="section-head"><h2>تفاصيل المنتجات</h2><p>هيكل جاهز مستقبلًا للربط مع لوحة تحكم وإدارة مخزون.</p></div>{products.slice(0,3).map(p=><div id={`product-${p.id}`} className="detail" key={p.id}><img src={p.image} alt={p.name}/><div><span className="tag">{p.category}</span><h3>{p.name}</h3><p>{p.long}</p><b>{p.price}</b><a className="btn ghost dark" href={`https://wa.me/${whatsappNumber}?text=${encodeURIComponent('أريد تفاصيل '+p.name)}`}>اطلبي التفاصيل</a></div></div>)}</section>}
function Contact(){return <section id="التواصل" className="contact"><div><span className="eyebrow"><Phone size={18}/> تواصلي معنا</span><h2>جاهزون لمساعدتك في اختيار إطلالتك القادمة</h2><p><MapPin size={18}/> صنعاء، اليمن — يمكن تعديل الموقع لاحقًا</p><div className="social"><a href={`https://wa.me/${whatsappNumber}`}><MessageCircle/> واتساب</a><a href="#"><Instagram/> إنستغرام</a></div></div></section>}
function Footer(){return <footer><b>تصاميم</b><p>فساتين سهرة وجلابيات نسائية فاخرة — تجربة رقمية لبراند عربي أنيق.</p><small>© 2026 TASAMMEM. All rights reserved.</small></footer>}
function App(){const [loading,setLoading]=useState(true); React.useEffect(()=>{const t=setTimeout(()=>setLoading(false),900);return()=>clearTimeout(t)},[]);return <>{loading?<div className="loader"><span>تصاميم</span></div>:<><Navbar/><main><Hero/><Products/><SplitSection id="الفساتين" title="فساتين للمناسبات التي لا تُنسى" text="فساتين سهرة، مناسبات، وتصاميم خاصة بلمسات أنثوية فاخرة تناسب الذوق العربي." img="https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85"/><SplitSection id="الجلابيات" reverse title="جلابيات راقية بلمسة عصرية" text="مجموعة جلابيات تجمع الراحة والفخامة لتكوني متألقة في الزيارات والمناسبات." img="https://images.unsplash.com/photo-1545291730-faff8ca1d4b0?auto=format&fit=crop&w=900&q=85"/><Why/><Gallery/><Reviews/><Details/><Contact/></main><Footer/></>}</>}

createRoot(document.getElementById('root')).render(<App />)
